
name: Ejercicio de acción javascript
description: 'Acción de saludo'
inputs:
  nombre:
    required: false
    type: string
    default: John Doe
    description: "Tu nombre para el saludo"
outputs:
  saludo:
    value: ${{ steps.dado1.outputs.dado1 }}
  dado2: 
    value: ${{ steps.dado1.outputs.dado2 }}
runs:
  using: 'node20'
  main: 'dist/index.js'